# Generated by Django 3.2.6 on 2021-09-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('customer_age', models.IntegerField()),
                ('contact_no', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('booking_date', models.DateField()),
            ],
        ),
    ]
